"""
Test for publishing to ArcGIS Online
(`fimbench.publish.PublishFIMExtent2ArcGISOnline`).

Creates or updates a hosted feature layer from the FIM extents GeoJSON.
"""

import os

import pytest

# Connect to GIS using OAuth
CLIENT_ID = "m4zR1DBSDiJQpxsH"
published_item = ""


def test_publisher_importable():
    """The AGOL publisher is exposed by fimbench.publish (lazy import)."""
    arcgis = pytest.importorskip("arcgis", reason="install with .[publish]")
    from fimbench.publish import PublishFIMExtent2ArcGISOnline

    assert PublishFIMExtent2ArcGISOnline is not None


@pytest.mark.skipif(
    os.environ.get("FIMBENCH_LIVE") != "1",
    reason="opens OAuth and publishes to AGOL; set FIMBENCH_LIVE=1 to run",
)
def test_publish_to_agol():
    pytest.importorskip("arcgis", reason="install with .[publish]")
    from fimbench.publish import PublishFIMExtent2ArcGISOnline

    # (i) Setup GIS connection
    gis = PublishFIMExtent2ArcGISOnline.connect_gis_oauth(client_id=CLIENT_ID)

    # (ii) Initialize the publisher instance
    publisher = PublishFIMExtent2ArcGISOnline(
        mode_used="init",
        geojson_item_id=None,
        feature_layer_item_id="",
        feature_layer_url=None,
        feature_layer_title=None,
    )

    # (iii) Upsert the GeoJSON generated by the catalog builder
    result = publisher.upsert_geojson_feature_layer(
        gis=gis,
        geojson_path="./out/FIM_extents.geojson",
        mode="auto",  # Create new or update based on published_item_id provided
        published_item_id=None,  # Existing hosted feature layer item id to update, else None to create
        title="BenchFIMExtents",
        tags="FIM, Flood Mapping, Benchmark FIM, Aerial Flood Extents, Hydrology, Planet, Sentinel",
        summary="Curated benchmark Flood Inundation Maps (FIMs) from remote sensing, aerial observations, "
        "and hydrodynamic models. Organized into quality-based tiers with HWM-derived flood maps. "
        "Hosted on AWS S3 with open API access.",
        description="Flood Inundation Mapping Benchmark (FIMbench) Repository- This repository provides a curated collection of benchmark Flood Inundation Maps (FIMs) "
        "derived from multiple high-quality sources, including remote sensing imagery, aerial observations, and high-fidelity hydrodynamic model outputs. "
        "The complete FIM inventory is organized into four quality-based tiers, along with an additional category containing High Water Mark (HWM)-derived flood maps. "
        "All benchmark datasets are hosted in an AWS S3 bucket and can be accessed through an open API, enabling seamless integration into research pipelines, "
        "visualization tools, and operational workflows.",
        folder="BenchFIMData",
    )

    # (iv) Print results
    print(f"\nSuccessfully {result.mode_used} layer!")
    print(f"GeoJSON Item ID: {result.geojson_item_id}")
    print(f"Feature Layer Item ID: {result.feature_layer_item_id}")
    print(f"Feature Layer URL: {result.feature_layer_url}")
    print(f"Feature Layer Title: {result.feature_layer_title}")

    # (v) Assertions for pytest
    assert result.feature_layer_item_id is not None
    assert result.feature_layer_url is not None
    assert result.mode_used == "new"
